dist: xenial
language: node_js
node_js:
  - '12'

branches:
  - master

install:
  - npm ci

script:
  - npm run build

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    node_js: 12
    on:
      tags: false
      branch: master
